// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentationSidebar: [{ type: "autogenerated", dirName: "documentation" }],
  featuresSidebar: [{ type: "autogenerated", dirName: "features" }],
  // Single Reference tab: hand-authored guides pinned above the schema-generated
  // type pages. Guides live in docs/reference-guides/ (committed); the type pages
  // in docs/reference/ (generated).
  referenceSidebar: [
    {
      type: "category",
      label: "Guides",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "reference-guides" }],
    },
    {
      type: "category",
      label: "Schema reference",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "reference" }],
    },
  ],
  tutorialSidebar: [{ type: "autogenerated", dirName: "tutorials" }],
  exampleSidebar: [{ type: "autogenerated", dirName: "examples" }],
};

export default sidebars;
