// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  configurationSidebar: [{ type: "autogenerated", dirName: "configuration" }],
  documentationSidebar: [{ type: "autogenerated", dirName: "documentation" }],
  exampleSidebar: [{ type: "autogenerated", dirName: "examples" }],
};

export default sidebars;
